[greeter]
background=/usr/share/backgrounds/horizon-dark-greeter.jpg
background-color=#1e181a
theme-name=HorizonDark
icon-theme-name=Adwaita
font-name=Hack Nerd Font Mono 9
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
xft-dpi=163
user-background=false
