[greeter]
background=/usr/share/backgrounds/horizon-dark-greeter.jpg
theme-name=HorizonDark
icon-theme-name=Adwaita
font-name=Hack Nerd Font Mono 11
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
user-background=true
