pulse.rules = [
    {
        matches = [
            { application.name = "Spotify" }
            { application.process.binary = "spotify" }
        ]
        actions = { update-props = { node.target = "Bus-Music" } }
    }
    {
        matches = [
            { application.name = "Firefox" }
            { application.process.binary = "firefox" }
        ]
        actions = { update-props = { node.target = "Bus-Music" } }
    }
    {
        matches = [
            { application.name = "vlc" }
            { application.name = "VLC media player" }
            { application.process.binary = "vlc" }
        ]
        actions = { update-props = { node.target = "Bus-Music" } }
    }
    {
        matches = [
            { application.name = "Discord" }
            { application.process.binary = "Discord" }
            { application.process.binary = "discord" }
            { application.process.binary = "vesktop" }
        ]
        actions = { update-props = { node.target = "Bus-Voice" } }
    }
]
